site_name: Delta Simulations Docs
site_url: https://www.deltasimulations.ca
site_dir: dist/docs
plugins:
- glightbox
- search
theme:
  name: material
  favicon: Assets/Favicon.ico
  logo: Assets/delta.png
  features:
    - navigation.path
    - navigation.tracking
    - search.suggest
    - search.share
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
use_directory_urls: true
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - styles.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Delta-Simulations
      name: GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.gg/4pjxYUw8j7
      name: Discord
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@DeltaSimulations
      name: YouTube
  
